#!/usr/bin/env ruby

require_relative 'lib/bouch'

if ARGV[0].eql?(nil)
  puts 'Please supply budget pouch YAML file path and rerun bouch.'
  puts "Usage: #{$PROGRAM_NAME} [YAML_FILE]"
  exit 1
else
  budget = Bouch.new(ARGV[0])
  budget.show_budget
end
